#ifndef ERRORS_H
#define ERRORS_H

// Error Definitions
enum error_types {ERROR_NO_ERROR, ERROR_MOVEMENT_TOO_LARGE, ERROR_OUT_OF_RANGE,
                  ERROR_WRONG_NUMBER_OF_ARGUMENTS, ERROR_INVALID_AXIS, ERROR_UNSPECIFIED,
                  ERROR_NOT_ENABLED, ERROR_UNKNOWN_COMMAND};

#endif //ERRORS_H